//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class infoCompany
    {
        public int id { get; set; }
        public string tenCTy { get; set; }
        public string diaChi { get; set; }
        public string mail { get; set; }
        public string sdt { get; set; }
        public string sdtBan { get; set; }
        public string sdtDD { get; set; }
        public string image { get; set; }
        public string fb { get; set; }
        public string googlePlus { get; set; }
        public string youtube { get; set; }
        public string twitter { get; set; }
    }
}
